language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t cgpb89/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true cgpb89/docker-react npm run test